export const COLLECTIONS = {
  USERS: 'users',
  EVENTS: 'events',
  COMMUNITIES: 'communities',
  LISTINGS: 'listings',
  CHATS: 'chats',
  MESSAGES: 'messages',
  ATTENDEES: 'attendees',
  MEMBERS: 'members',
  POSTS: 'posts',
  COMMENTS: 'comments',
  NOTIFICATIONS: 'notifications',
  JOIN_REQUESTS: 'joinRequests',
  SAVED_EVENTS: 'savedEvents',
  SAVED_LISTINGS: 'savedListings',
  SAVES: 'saves',
  FOLLOWS: 'follows',
};
