export const DISCOVER_CATEGORIES = [
  {
    id: 'all',
    label: 'Tümü',
    value: null,
    icon: '⌁',
    color: '#2563EB',
  },
  {
    id: 'concert',
    label: 'Konser',
    value: 'Konser',
    icon: '♪',
    color: '#7C3AED',
  },
  {
    id: 'seminar',
    label: 'Seminer',
    value: 'Seminer',
    icon: '⌕',
    color: '#0EA5E9',
  },
  {
    id: 'sport',
    label: 'Spor',
    value: 'Spor',
    icon: '●',
    color: '#16A34A',
  },
  {
    id: 'club',
    label: 'Kulüp',
    value: 'Kulüp',
    icon: '♟',
    color: '#F97316',
  },
  {
    id: 'game',
    label: 'Oyun',
    value: 'Oyun',
    icon: '⌘',
    color: '#DB2777',
  },
  {
    id: 'art',
    label: 'Sanat',
    value: 'Sanat',
    icon: '✦',
    color: '#9333EA',
  },
  {
    id: 'festival',
    label: 'Festival',
    value: 'Festival',
    icon: '✺',
    color: '#EAB308',
  },
  {
    id: 'other',
    label: 'Diğer',
    value: 'Diğer',
    icon: '•',
    color: '#64748B',
  },
];
