export const ROUTES = {
  LOGIN: 'Login',
  REGISTER: 'Register',
  FORGOT_PASSWORD: 'ForgotPassword',
  PROFILE_COMPLETION: 'ProfileCompletion',
  DISCOVER: 'Discover',
  EVENT_DETAIL: 'EventDetail',
  CREATE_EVENT: 'CreateEvent',
  COMMUNITY_LIST: 'CommunityList',
  COMMUNITY_DETAIL: 'CommunityDetail',
  POST_DETAIL: 'PostDetail',
  CREATE_COMMUNITY: 'CreateCommunity',
  MARKET_HOME: 'MarketHome',
  LISTING_DETAIL: 'ListingDetail',
  CREATE_LISTING: 'CreateListing',
  MY_LISTINGS: 'MyListings',
  CHAT_LIST: 'ChatList',
  CHAT_DETAIL: 'ChatDetail',
  PROFILE: 'Profile',
  EDIT_PROFILE: 'EditProfile',
  USER_PROFILE: 'UserProfile',
  SETTINGS: 'Settings',
  NOTIFICATIONS: 'Notifications',
};
