import { ROUTES } from '../constants/routes';

export const authRoutes = [
  ROUTES.LOGIN,
  ROUTES.REGISTER,
  ROUTES.FORGOT_PASSWORD,
  ROUTES.PROFILE_COMPLETION,
];

export const mainTabs = [
  ROUTES.DISCOVER,
  ROUTES.COMMUNITY_LIST,
  ROUTES.MARKET_HOME,
  ROUTES.CHAT_LIST,
  ROUTES.PROFILE,
];

export const modalRoutes = [
  ROUTES.CREATE_EVENT,
  ROUTES.CREATE_COMMUNITY,
  ROUTES.CREATE_LISTING,
  ROUTES.EDIT_PROFILE,
  ROUTES.NOTIFICATIONS,
];
